### ISSUE TITLE
How to use it for another dataset

### ISSUE THREAD

**Issue by mrinal18** [bourdakos1/capsule-networks#2]
Hey, i am having problem intergrating this with another dataset 
it includes folders as label and different images in it.

Class1/
image1.jpg
image2.jpg

Class2/
image1.jpg
image2.jpg

.
.
.

Can you help me with this issue?

**Comment by bourdakos1** [comment]
Hi there!

Are the images greyscale? The code currently only works with one color channel

**Comment by mrinal18** [comment]
no it is not currently, but even if i make image greyscale, how do i train my dataset with this model? 

i want to use this model for object detection

**Comment by bourdakos1** [comment]
I'm currently working on a new version with the ability to train on a more complicated dataset than MNIST. I will try to make it more straight forward on adding your own data

**Comment by mrinal18** [comment]
@bourdakos1 Do guide me on how you used it for complicated dataset. Thank you
